//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kvar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kvar()
        {
            this.Rad_na_kvarovima = new HashSet<Rad_na_kvarovima>();
        }
    
        public int ID_kvara { get; set; }
        public string Opis { get; set; }
        public System.DateTime Datum_prijave { get; set; }
        public string Status { get; set; }
        public int ID_jedinice { get; set; }
    
        public virtual Smjestajna_jedinica Smjestajna_jedinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rad_na_kvarovima> Rad_na_kvarovima { get; set; }
    }
}
