//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsDomDBEntities : DbContext
    {
        public StudentsDomDBEntities()
            : base("name=StudentsDomDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Kreira> Kreira { get; set; }
        public virtual DbSet<Kvar> Kvar { get; set; }
        public virtual DbSet<Placanje> Placanje { get; set; }
        public virtual DbSet<Podnesena> Podnesena { get; set; }
        public virtual DbSet<Povijest_rezervacija> Povijest_rezervacija { get; set; }
        public virtual DbSet<Prituzba> Prituzba { get; set; }
        public virtual DbSet<Rad_na_kvarovima> Rad_na_kvarovima { get; set; }
        public virtual DbSet<Rezervacija> Rezervacija { get; set; }
        public virtual DbSet<Smjestajna_jedinica> Smjestajna_jedinica { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Tip_smjestaja> Tip_smjestaja { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
