//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placanje
    {
        public int ID_placanja { get; set; }
        public decimal Iznos { get; set; }
        public System.DateTime Datum_placanja { get; set; }
        public string Nacin_placanja { get; set; }
        public int ID_rezervacije { get; set; }
    
        public virtual Rezervacija Rezervacija { get; set; }
    }
}
