//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podnesena
    {
        public int ID_student { get; set; }
        public int ID_prituzbe { get; set; }
        public string Kategorija_prituzbe { get; set; }
    
        public virtual Prituzba Prituzba { get; set; }
        public virtual Student Student { get; set; }
    }
}
