//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Povijest_rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Povijest_rezervacija()
        {
            this.Kreira = new HashSet<Kreira>();
        }
    
        public int ID_povijesti { get; set; }
        public System.DateTime Datum_izmjene { get; set; }
        public string Opis_izmjene { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kreira> Kreira { get; set; }
    }
}
