//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rad_na_kvarovima
    {
        public int ID_admin { get; set; }
        public int ID_zaposlenika { get; set; }
        public int ID_kvar { get; set; }
        public System.DateTime Datum_rada { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Kvar Kvar { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
