//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija()
        {
            this.Kreira = new HashSet<Kreira>();
            this.Placanje = new HashSet<Placanje>();
        }
    
        public int ID_rezervacije { get; set; }
        public System.DateTime Datum_rezervacije { get; set; }
        public System.DateTime Datum_pocetka { get; set; }
        public System.DateTime Datum_zavrsetka { get; set; }
        public int ID_jedinice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kreira> Kreira { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Placanje> Placanje { get; set; }
        public virtual Smjestajna_jedinica Smjestajna_jedinica { get; set; }
    }
}
