//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smjestajna_jedinica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Smjestajna_jedinica()
        {
            this.Kvar = new HashSet<Kvar>();
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int ID_jedinice { get; set; }
        public string Broj_sobe { get; set; }
        public int Kapacitet { get; set; }
        public int Tip_sobe { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kvar> Kvar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
        public virtual Tip_smjestaja Tip_smjestaja { get; set; }
    }
}
