//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze_podataka_2_projekni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip_smjestaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tip_smjestaja()
        {
            this.Smjestajna_jedinica = new HashSet<Smjestajna_jedinica>();
        }
    
        public int ID_tipa { get; set; }
        public string Opis { get; set; }
        public decimal Cijena_po_nocenju { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smjestajna_jedinica> Smjestajna_jedinica { get; set; }
    }
}
